spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: primesoft
 
  jpa:
     properties:
          hibernate:
                jdbc.lob.non_contextual_creation= true
                dialect= org.hibernate.dialect.PostgreSQLDialect
                ddl-auto= update
server:
   port: 9099
  
My application Properties: spring.batch.job.enabled=false